# Generated by Django 4.2.7 on 2023-11-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('morador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_visita', models.CharField(max_length=255)),
                ('quantidade_pessoas', models.IntegerField()),
                ('pessoa_doente', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50)),
                ('pessoa_sintoma', models.IntegerField()),
                ('sintomas', models.TextField()),
                ('data_visita', models.DateField()),
                ('dengue', models.BooleanField()),
                ('dengue_hemorragica', models.BooleanField()),
                ('chikungunya', models.BooleanField()),
                ('zika', models.BooleanField()),
                ('descricao', models.TextField()),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
            ],
        ),
    ]
