# Generated by Django 4.2.7 on 2023-11-23 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='name',
        ),
    ]
