# Generated by Django 4.2.6 on 2023-11-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bairro', '0001_initial'),
        ('morador', '0001_initial'),
        ('rua', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_propriedade', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial')], max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('referencia', models.CharField(max_length=100)),
                ('reservatorio', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bairro.bairro')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morador.morador')),
                ('rua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rua.rua')),
            ],
        ),
    ]
