# Generated by Django 4.2.7 on 2023-12-28 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa_agua', models.BooleanField()),
                ('materiais_rodantes', models.BooleanField()),
                ('depositos_moveis', models.BooleanField()),
                ('depositos_naturais', models.BooleanField()),
                ('depositos_fixos', models.BooleanField()),
                ('outros_depositos', models.BooleanField()),
                ('larvicida', models.CharField(choices=[('Biológico', 'Biológico'), ('Químico', 'Químico'), ('Nenhum', 'Nenhum')], max_length=50)),
                ('quantidade_l', models.IntegerField()),
                ('focos', models.CharField(choices=[('Não há focos', 'Não há focos'), ('Tem água parada, mas sem a presença de mosquitos', 'Tem água parada, mas sem a presença de mosquitos'), ('Água parada e presença de mosquitos', 'Água parada e presença de mosquitos')], max_length=50)),
                ('resumo_visita', models.TextField()),
                ('data_visita', models.DateField()),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
        ),
    ]
