# Generated by Django 4.2.7 on 2023-12-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita1',
            name='focos',
            field=models.CharField(choices=[('sem_focos', 'Não há focos'), ('agua_parada_sem_mosquitos', 'Tem água parada, mas sem a presença de mosquitos'), ('agua_parada_com_mosquitos', 'Água parada e presença de mosquitos')], max_length=50),
        ),
    ]
