# Generated by Django 4.2.7 on 2023-12-29 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visita1', '0002_alter_visita1_focos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita1',
            name='focos',
            field=models.CharField(choices=[('Sem focos', 'Não há focos'), ('Água parada, sem mosquitos', 'Tem água parada, mas sem a presença de mosquitos'), ('Água parada, com mosquitos', 'Água parada e presença de mosquitos')], max_length=50),
        ),
    ]
