# Generated by Django 4.2.6 on 2023-11-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('sus', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Transgênero', 'Transgênero'), ('Gênero Neutro', 'Gênero Neutro'), ('Não-binário', 'Não-binário'), ('Prefiro não responder', 'Prefiro não responder'), ('Outro', 'Outro')], max_length=100)),
                ('telefone', models.CharField(max_length=50)),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
